import './globals.css'
import { Montserrat, Russo_One } from 'next/font/google'

const russo = Russo_One({ subsets: ['latin'], weight: ['400']  })
const montserrat = Montserrat({ subsets: ['latin'], weight:['100','300','400','700']})

export const metadata = {
  title: 'Pokedex',
  description: 'Generated by JonisCbum',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={russo.className}>{children}</body>
    </html>
  )
}
